name = "reflect-net-east"
main = "demo/worker/index.ts"
compatibility_date = "2022-11-30"
account_id = "085f6d8eb08e5b23debfb08b21bda1eb"
logpush = false

route = { pattern = "reflect-server.net", custom_domain = true }
durable_objects.bindings = [
  { name = "roomDO", class_name = "RoomDO" },
  { name = "authDO", class_name = "AuthDO" }
]
var = { DATADOG_SERVICE_LABEL = "reflect.net", LOG_LEVEL = "info"}

[[migrations]]
tag = "v1"
new_classes = ["Server"]

[[migrations]]
tag = "v2"
renamed_classes = [{from = "Server", to = "RoomDO" }]
new_classes = ["AuthDO"]


[build]
# don't watch all resources because we want to run without --persist when
# possible, so restarts delete data.
watch_dir = "demo/worker"

[triggers]
crons = [ "*/5 * * * *" ] # ever 5 mins for AuthDO connection revalidation

#[secrets]
#DATADOG_LOGS_API_KEY
#DATADOG_METRICS_API_KEY
#REFLECT_AUTH_API_KEY
#NEW_ROOM_SECRET


[env.staging]
name = "reflect-net-east-staging"
route = { pattern = "staging.reflect-server.net", custom_domain = true }
durable_objects.bindings = [
  { name = "roomDO", class_name = "RoomDO" },
  { name = "authDO", class_name = "AuthDO" }
]
var = { DATADOG_SERVICE_LABEL = "staging.reflect.net", LOG_LEVEL = "debug" }
