packages:
  - 'apps/*'
  - 'packages/*'
  - 'prod'
  - 'tools/*'
publicHoistPattern:
  - '*'
allowBuilds:
  '@prisma/engines': true
  '@rocicorp/zero-sqlite3': true
  core-js: true
  core-js-pure: true
  cpu-features: true
  esbuild: true
  prisma: true
  protobufjs: true
  ssh2: true
