packages:
  - 'apps/*'
  - 'packages/*'
  - 'prod'
  - 'tools/*'
allowBuilds:
  '@prisma/engines': true
  '@rocicorp/zero-sqlite3': true
  core-js: false
  core-js-pure: false
  cpu-features: false
  esbuild: true
  prisma: true
  protobufjs: true
  ssh2: false
overrides:
  webpackbar: ^7.0.0
