name = "replidraw-do-grgbkr"
main = "worker/index.ts"
compatibility_date = "2022-06-03"


[durable_objects]
bindings = [
  { name = "roomDO", class_name = "RoomDO" },
]

[[migrations]]
tag = "v1"
new_classes = ["Server"]

[[migrations]]
tag = "v2"
renamed_classes = [{from = "Server", to = "RoomDO" }]
new_classes = ["AuthDO"]

[[migrations]]
tag = "v3"
deleted_classes = ["AuthDO"]

#[secrets]
#DATADOG_API_KEY
