/**
 * Generated by tsnapi — public API snapshot of `replicache/expo-sqlite`
 */
// #region Re-exports
export { expoSQLiteStoreProvider, type ExpoSQLiteStoreOptions, } from './kv/expo-sqlite/store.ts';
// #endregion