/**
 * Generated by tsnapi — public API snapshot of `replicache/impl`
 */
// #region Re-exports
export type { PatchOperationInternal } from './patch-operation.ts';
export type { PokeInternal } from './types.ts';
export { ReplicacheImpl, type ReplicacheImplOptions } from './replicache-impl.ts';
// #endregion