/**
 * Generated by tsnapi — public API snapshot of `replicache/op-sqlite`
 */
// #region Re-exports
export { opSQLiteStoreProvider, type OpSQLiteStoreOptions, } from './kv/op-sqlite/store.ts';
// #endregion