import {assert} from '../../../shared/src/asserts.ts';
import {id, lit} from '../types/sql.ts';
import type {IndexPredicate, IndexPredicateValue} from './specs.ts';

const CANONICAL_INTEGER_RE = /^-?(?:0|[1-9]\d*)$/;
const TRAILING_SEMICOLON_RE = /;$/;
const IDENTIFIER_CHAR_RE = /[A-Za-z0-9_$]/;
const WHITESPACE_RE = /\s/;
const COMPARISON_TOKEN_RE = /^(?:<>|<=|>=|=|<|>)/;
const INTEGER_TOKEN_RE = /^-?(?:0|[1-9]\d*)/;
const WORD_TOKEN_RE = /^[A-Za-z_][A-Za-z0-9_$]*/;

export function liteIndexPredicateSQL(predicate: IndexPredicate): string {
  switch (predicate.type) {
    case 'and':
    case 'or':
      assert(predicate.conditions.length > 0, 'empty index predicate');
      return `(${predicate.conditions
        .map(liteIndexPredicateSQL)
        .join(` ${predicate.type.toUpperCase()} `)})`;
    case 'not':
      return `(NOT ${liteIndexPredicateSQL(predicate.condition)})`;
    case 'null-test':
      return `${id(predicate.column)} ${predicate.op}`;
    case 'comparison':
      return `${id(predicate.column)} ${predicate.op} ${predicateValueSQL(
        predicate.value,
      )}`;
  }
}

function predicateValueSQL(value: IndexPredicateValue): string {
  switch (value.type) {
    case 'boolean':
      return value.value ? '1' : '0';
    case 'integer':
      // The PostgreSQL translator only constructs canonical decimal integers.
      assert(
        CANONICAL_INTEGER_RE.test(value.value),
        'invalid integer predicate',
      );
      return value.value;
    case 'string':
      return lit(value.value);
  }
}

export function mapIndexPredicateColumns(
  predicate: IndexPredicate,
  map: (column: string) => string,
): IndexPredicate {
  switch (predicate.type) {
    case 'and':
    case 'or':
      return {
        ...predicate,
        conditions: predicate.conditions.map(condition =>
          mapIndexPredicateColumns(condition, map),
        ),
      };
    case 'not':
      return {
        ...predicate,
        condition: mapIndexPredicateColumns(predicate.condition, map),
      };
    case 'null-test':
    case 'comparison':
      return {...predicate, column: map(predicate.column)};
  }
}

/**
 * Finds the WHERE clause in a CREATE INDEX statement generated by SQLite.
 * The scan deliberately skips quoted text and nested parentheses.
 */
export function extractLiteIndexPredicateSQL(sql: string): string {
  let depth = 0;
  let quote: '"' | "'" | '`' | ']' | undefined;
  for (let i = 0; i < sql.length; i++) {
    const char = sql[i];
    if (quote) {
      if (quote === ']') {
        if (char === ']') quote = undefined;
      } else if (char === quote) {
        if (sql[i + 1] === quote) {
          i++;
        } else {
          quote = undefined;
        }
      }
      continue;
    }
    if (char === '"' || char === "'" || char === '`') {
      quote = char;
      continue;
    }
    if (char === '[') {
      quote = ']';
      continue;
    }
    if (char === '(') {
      depth++;
      continue;
    }
    if (char === ')') {
      depth--;
      continue;
    }
    if (
      depth === 0 &&
      sql.slice(i, i + 5).toUpperCase() === 'WHERE' &&
      !isIdentifierChar(sql[i - 1]) &&
      !isIdentifierChar(sql[i + 5])
    ) {
      const predicate = sql
        .slice(i + 5)
        .trim()
        .replace(TRAILING_SEMICOLON_RE, '')
        .trim();
      assert(predicate.length > 0, 'partial index has an empty WHERE clause');
      return predicate;
    }
  }
  throw new Error('partial index SQL has no top-level WHERE clause');
}

function isIdentifierChar(char: string | undefined): boolean {
  return char !== undefined && IDENTIFIER_CHAR_RE.test(char);
}

type Token =
  | {type: 'identifier'; value: string}
  | {type: 'string'; value: string}
  | {type: 'integer'; value: string}
  | {
      type:
        | '('
        | ')'
        | '='
        | '<>'
        | '<'
        | '<='
        | '>'
        | '>='
        | 'AND'
        | 'OR'
        | 'NOT'
        | 'IS'
        | 'NULL'
        | 'EOF';
    };

/** Parses only the canonical SQL emitted by {@link liteIndexPredicateSQL}. */
export function parseLiteIndexPredicateSQL(
  sql: string,
  isBooleanColumn: (column: string) => boolean = () => false,
): IndexPredicate {
  const parser = new LitePredicateParser(
    tokenizeLitePredicate(sql),
    isBooleanColumn,
  );
  const predicate = parser.parse();
  parser.expect('EOF');
  return predicate;
}

class LitePredicateParser {
  readonly #tokens: readonly Token[];
  readonly #isBooleanColumn: (column: string) => boolean;
  #position = 0;

  constructor(
    tokens: readonly Token[],
    isBooleanColumn: (column: string) => boolean,
  ) {
    this.#tokens = tokens;
    this.#isBooleanColumn = isBooleanColumn;
  }

  parse(): IndexPredicate {
    return this.#parseOr();
  }

  #parseOr(): IndexPredicate {
    const conditions = [this.#parseAnd()];
    while (this.#take('OR')) conditions.push(this.#parseAnd());
    return conditions.length === 1
      ? conditions[0]
      : {type: 'or', conditions: flatten('or', conditions)};
  }

  #parseAnd(): IndexPredicate {
    const conditions = [this.#parseNot()];
    while (this.#take('AND')) conditions.push(this.#parseNot());
    return conditions.length === 1
      ? conditions[0]
      : {type: 'and', conditions: flatten('and', conditions)};
  }

  #parseNot(): IndexPredicate {
    if (this.#take('NOT')) {
      return {type: 'not', condition: this.#parseNot()};
    }
    if (this.#take('(')) {
      const predicate = this.#parseOr();
      this.expect(')');
      return predicate;
    }
    return this.#parseAtomic();
  }

  #parseAtomic(): IndexPredicate {
    const column = this.#expectValue('identifier');
    if (this.#take('IS')) {
      const not = this.#take('NOT');
      this.expect('NULL');
      return {
        type: 'null-test',
        column,
        op: not ? 'IS NOT NULL' : 'IS NULL',
      };
    }
    const token = this.#tokens[this.#position++];
    if (!isComparison(token?.type)) {
      throw new Error(
        `expected comparison operator in partial index predicate`,
      );
    }
    const value = this.#parseValue(column);
    return {type: 'comparison', column, op: token.type, value};
  }

  #parseValue(column: string): IndexPredicateValue {
    const token = this.#tokens[this.#position++];
    switch (token?.type) {
      case 'integer':
        if (
          this.#isBooleanColumn(column) &&
          (token.value === '0' || token.value === '1')
        ) {
          return {type: 'boolean', value: token.value === '1'};
        }
        return {type: 'integer', value: token.value};
      case 'string':
        return {type: 'string', value: token.value};
      default:
        throw new Error('expected predicate literal');
    }
  }

  #take(type: Token['type']): boolean {
    if (this.#tokens[this.#position]?.type !== type) return false;
    this.#position++;
    return true;
  }

  expect(type: Token['type']): void {
    if (!this.#take(type)) throw new Error(`expected ${type}`);
  }

  #expectValue(type: 'identifier'): string {
    const token = this.#tokens[this.#position++];
    if (token?.type !== type) throw new Error(`expected ${type}`);
    return token.value;
  }
}

function flatten(
  type: 'and' | 'or',
  conditions: readonly IndexPredicate[],
): readonly IndexPredicate[] {
  return conditions.flatMap(condition =>
    condition.type === type ? condition.conditions : [condition],
  );
}

function isComparison(
  type: Token['type'] | undefined,
): type is '=' | '<>' | '<' | '<=' | '>' | '>=' {
  return (
    type === '=' ||
    type === '<>' ||
    type === '<' ||
    type === '<=' ||
    type === '>' ||
    type === '>='
  );
}

function tokenizeLitePredicate(sql: string): Token[] {
  const tokens: Token[] = [];
  for (let i = 0; i < sql.length;) {
    const char = sql[i];
    if (WHITESPACE_RE.test(char)) {
      i++;
      continue;
    }
    if (char === '"') {
      const parsed = readQuoted(sql, i, '"');
      tokens.push({type: 'identifier', value: parsed.value});
      i = parsed.end;
      continue;
    }
    if (char === "'") {
      const parsed = readQuoted(sql, i, "'");
      tokens.push({type: 'string', value: parsed.value});
      i = parsed.end;
      continue;
    }
    const comparison = COMPARISON_TOKEN_RE.exec(sql.slice(i))?.[0];
    if (comparison) {
      tokens.push({type: comparison as '=' | '<>' | '<' | '<=' | '>' | '>='});
      i += comparison.length;
      continue;
    }
    if (char === '(' || char === ')') {
      tokens.push({type: char});
      i++;
      continue;
    }
    const integer = INTEGER_TOKEN_RE.exec(sql.slice(i))?.[0];
    if (integer) {
      tokens.push({type: 'integer', value: integer});
      i += integer.length;
      continue;
    }
    const word = WORD_TOKEN_RE.exec(sql.slice(i))?.[0];
    if (word) {
      const keyword = word.toUpperCase();
      if (
        keyword === 'AND' ||
        keyword === 'OR' ||
        keyword === 'NOT' ||
        keyword === 'IS' ||
        keyword === 'NULL'
      ) {
        tokens.push({type: keyword});
      } else {
        tokens.push({type: 'identifier', value: word.toLowerCase()});
      }
      i += word.length;
      continue;
    }
    throw new Error(`unsupported token in partial index predicate at ${i}`);
  }
  tokens.push({type: 'EOF'});
  return tokens;
}

function readQuoted(
  sql: string,
  start: number,
  quote: '"' | "'",
): {value: string; end: number} {
  let value = '';
  for (let i = start + 1; i < sql.length; i++) {
    if (sql[i] !== quote) {
      value += sql[i];
      continue;
    }
    if (sql[i + 1] === quote) {
      value += quote;
      i++;
      continue;
    }
    return {value, end: i + 1};
  }
  throw new Error('unterminated quoted value in partial index predicate');
}
