/**
 * Generated by tsnapi — public API snapshot of `@rocicorp/zero/change-protocol/v0`
 */
// #region Re-exports
export * from '../../../zero-cache/src/services/change-source/protocol/mod.ts';
// #endregion