name = "zero-cache"
type = "javascript"

account_id = ""
workers_dev = true

compatibility_date = "2024-04-29"
compatibility_flags = []

[durable_objects]
bindings = [
  { name = "runnerDO", class_name = "ServiceRunnerDO" },
]

[build.upload]
format = "modules"
dir = "out"
main = "./tool/miniflare-environment.js"

[miniflare]
durable_objects_persist = true
