name = "zero-service-runner"
main = "src/services/index.ts"
compatibility_date = "2024-04-03"
account_id = "085f6d8eb08e5b23debfb08b21bda1eb"
node_compat = true
logpush = true
durable_objects.bindings = [
  { name = "runnerDO", class_name = "RunnerDO" },
]

[vars]
LOG_LEVEL = "debug"
UPSTREAM_URI = "postgresql://postgres:RGRo44VYqkITVx48@db.fnsqmpzivtnqxnawcumg.supabase.co:5432/postgres"
SYNC_REPLICA_URI = "postgres://postgres:PflboBSekWHTkhJ4@ec2-3-74-16-137.eu-central-1.compute.amazonaws.com:5432/postgres"


[[migrations]]
tag = "v1"
new_classes = ["RunnerDO"]

[build]
# don't watch all resources because we want to run without --persist when
# possible, so restarts delete data.
watch_dir = "src/services"

#[triggers]
#crons = [ "*/5 * * * *" ] # ever 5 mins for AuthDO connection revalidation
