// @ts-check

import * as fs from 'node:fs/promises';
import * as path from 'node:path';
import {fileURLToPath} from 'node:url';
import * as esbuild from 'esbuild';
import {makeDefine, sharedOptions} from '../../shared/src/build.ts';

const dirname = path.dirname(fileURLToPath(import.meta.url));

async function buildIndex(): Promise<void> {
  const minify = true;
  const define = {
    ...makeDefine('release'),
    'import.meta.env': 'undefined',
  };
  await esbuild.build({
    ...sharedOptions(minify),
    external: ['node:*', 'expo*'],
    format: 'esm',
    platform: 'browser',
    splitting: true,
    define,
    outdir: path.join(dirname, '..', 'out'),
    entryPoints: [path.join(dirname, '..', 'src', 'index.ts')],
  });
}

/**
 * A single self-contained ESM file for React Native. Metro never resolves any
 * monorepo TypeScript: the runner copies this one file into the Expo app.
 */
async function buildRN(): Promise<void> {
  // Minified by default to match what ships, but Hermes CPU profiles are
  // unreadable without real function names — PERF_RN_NO_MINIFY=1 keeps them.
  const minify = process.env.PERF_RN_NO_MINIFY !== '1';
  const define = {
    ...makeDefine('release'),
    'import.meta.env': 'undefined',
    // Hermes cannot parse `import.meta` at all. The only use is the default
    // tmcw fixture URL, which the RN runner overrides via setTmcwUrl().
    'import.meta.url': '""',
  };
  await esbuild.build({
    ...sharedOptions(minify),
    external: ['node:*', 'expo-sqlite', '@op-engineering/op-sqlite'],
    format: 'esm',
    platform: 'neutral',
    // 'neutral' resolves no main fields at all, so any dependency that ships
    // only a legacy entry (rather than an `exports` map esbuild can follow)
    // fails to resolve outright.
    //
    // Metro resolves `react-native`, `browser`, `main`. We keep that order so a
    // dependency picks the same entry here as it would if Metro had bundled it,
    // and add `module` ahead of `main` only: where Metro would fall back to a
    // CommonJS `main`, esbuild prefers the ESM build so it can tree-shake. A
    // package that ships `browser` still gets it, as under Metro.
    mainFields: ['react-native', 'browser', 'module', 'main'],
    splitting: false,
    define,
    outfile: path.join(dirname, '..', 'out', 'rn.js'),
    entryPoints: [path.join(dirname, '..', 'src', 'rn.ts')],
  });
}

/**
 * The host app imports the bundle as a plain local file, so it needs a
 * declaration for it. Emitted here, beside `rn.ts`, so it cannot drift out of
 * sight in the app; the runner copies it in alongside the bundle.
 *
 * Only the surface the app itself uses. `BenchmarkResult` stays opaque because
 * the app never inspects a result — it formats it and posts it back.
 */
async function buildRNTypes(): Promise<void> {
  await fs.writeFile(
    path.join(dirname, '..', 'out', 'rn.d.ts'),
    `// Generated by tool/build.ts from src/rn.ts. Do not edit.
export type Backend = 'expo' | 'op' | 'mem';

/** Opaque to the host app: it formats results and posts them back. */
export type BenchmarkResult = {readonly __benchmarkResult: unique symbol};

export declare function configure(opts: {
  backend: Backend;
  tmcwUrl: string;
}): void;
export declare function formatAsReplicache(result: BenchmarkResult): string;
export declare function runBenchmarkByNameAndGroup(
  name: string,
  group: string,
): Promise<['result', BenchmarkResult] | ['error', unknown] | undefined>;
`,
  );
}

await buildIndex();
await buildRN();
await buildRNTypes();
