services:
  postgres_primary:
    extends:
      file: docker-compose.base.yml
      service: postgres_primary
    volumes:
      - zbugs_pgdata_upstream:/var/lib/postgresql/data
      - ./share_sql/base.sql:/docker-entrypoint-initdb.d/a.sql
      - ./github_upstream/init.sql:/docker-entrypoint-initdb.d/b.sql
      - ./share_sql/index.sql:/docker-entrypoint-initdb.d/c.sql
      - ./data/github:/data
  postgres_replica:
    extends:
      file: docker-compose.base.yml
      service: postgres_replica
  
  opensearch:
    image: opensearchproject/opensearch:2.11.1
    container_name: opensearch
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node
      - discovery.seed_hosts=opensearch
      - cluster.initial_cluster_manager_nodes=opensearch-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_SECURITY_PLUGIN=true"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600
    networks:
      - opensearch-net
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.11.1
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      - "OPENSEARCH_HOSTS=http://opensearch:9200"
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
    networks:
      - opensearch-net
    depends_on:
      opensearch:
        condition: service_healthy

volumes:
  zbugs_pgdata_sync:
    driver: local
  zbugs_pgdata_upstream:
    driver: local
  opensearch_data:
    driver: local

networks:
  opensearch-net:
    driver: bridge
