/**
 * Generated by tsnapi — public API snapshot of `@rocicorp/zero/analyze`
 */
// #region Re-exports
export { runAnalyzeCLI, type AnalyzeCLIOptions, } from '../../analyze-query/src/analyze-cli.ts';
// #endregion