/**
 * Generated by tsnapi — public API snapshot of `@rocicorp/zero/react-native`
 */
// #region Types
export type CreateStore = sqlite.CreateStore;
export type DropStore = sqlite.DropStore;
export type ExpoSQLiteStoreOptions = expo.ExpoSQLiteStoreOptions;
export type PreparedStatement = sqlite.PreparedStatement;
export type Read = sqlite.Read;
export type SQLiteDatabase = sqlite.SQLiteDatabase;
export type SQLiteStoreOptions = sqlite.SQLiteStoreOptions;
export type Store = sqlite.Store;
export type StoreProvider = sqlite.StoreProvider;
export type Write = sqlite.Write;
// #endregion

// #region Variables
export declare const clearAllNamedStoresForTesting: typeof sqlite.clearAllNamedStoresForTesting;
export declare const dropStore: typeof sqlite.dropStore;
export declare const expoSQLiteStoreProvider: typeof expo.expoSQLiteStoreProvider;
export declare const SQLiteStore: typeof sqlite.SQLiteStore;
// #endregion