export const cases: {
  pattern: string;
  flags: 'i' | '';
  inputs: [string, boolean][];
}[] = [
  {
    pattern: 'foo',
    flags: '',
    inputs: [
      ['foo', true],
      ['bar', false],
      ['Foo', false],
      ['FOO', false],
      ['fo', false],
      ['fooa', false],
      ['afoo', false],
      ['afoob', false],
    ],
  },
  {
    pattern: 'foo',
    flags: 'i',
    inputs: [
      ['foo', true],
      ['bar', false],
      ['Foo', true],
      ['FOO', true],
      ['fo', false],
      ['fooa', false],
      ['afoo', false],
      ['afoob', false],
    ],
  },
  {
    pattern: 'foo%',
    flags: '',
    inputs: [
      ['foo', true],
      ['foobar', true],
      ['bar', false],
      ['Foo', false],
      ['FOO', false],
      ['fo', false],
      ['fooa', true],
      ['afoo', false],
      ['afoob', false],
    ],
  },
  {
    pattern: 'foo%',
    flags: 'i',
    inputs: [
      ['foo', true],
      ['foobar', true],
      ['bar', false],
      ['Foo', true],
      ['FOO', true],
      ['fo', false],
      ['fooa', true],
      ['afoo', false],
      ['afoob', false],
      ['foo\nbar', true],
      ['foobar\nbaz', true],
    ],
  },
  {
    pattern: 'foo_',
    flags: '',
    inputs: [
      ['foo', false],
      ['foobar', false],
      ['foob', true],
      ['bar', false],
      ['Foo', false],
      ['FOO', false],
      ['fo', false],
      ['afoo', false],
      ['afoob', false],
      // 'fooa\nbar' is 8 chars; `foo_` matches exactly 4. Must be false (SQLite
      // returns 0). The previous `true` came from the buggy `m`/multiline flag
      // matching the interior line "fooa".
      ['fooa\nbar', false],
    ],
  },
  {
    // `%` and `_` must match newline characters (dotall), and the pattern must
    // match the whole string. A `m`/multiline flag would wrongly match a single
    // interior line. All verified against SQLite.
    pattern: 'a%b',
    flags: '',
    inputs: [
      ['a\nb', true],
      ['axb', true],
      ['ab', true],
      ['z\nab', false],
      ['a\nbz', false],
    ],
  },
  {
    pattern: 'a_b',
    flags: '',
    inputs: [
      ['a\nb', true],
      ['axb', true],
      ['ab', false],
      ['a\nbc', false],
    ],
  },
  {
    pattern: 'foo\\%',
    flags: '',
    inputs: [
      ['foo%', true],
      ['foobar', false],
      ['bar', false],
      ['Foo', false],
      ['FOO', false],
      ['fo', false],
      ['fooa', false],
      ['afoo', false],
      ['afoob', false],
    ],
  },
  {
    pattern: 'foo\\%',
    flags: 'i',
    inputs: [
      ['foo%', true],
      ['FOO%', true],
      ['foobar', false],
      ['bar', false],
      ['Foo', false],
      ['FOO', false],
      ['fo', false],
      ['fooa', false],
      ['afoo', false],
      ['afoob', false],
    ],
  },
  {
    pattern: 'foo\\_',
    flags: '',
    inputs: [
      ['foo_', true],
      ['FOO_', false],
      ['foobar', false],
      ['bar', false],
      ['Foo', false],
      ['FOO', false],
      ['fo', false],
      ['fooa', false],
      ['afoo', false],
      ['afoob', false],
    ],
  },
  {
    pattern: '%foo',
    flags: '',
    inputs: [
      ['foo', true],
      ['foobar', false],
      ['bar', false],
      ['Foo', false],
      ['FOO', false],
      ['fo', false],
      ['fooa', false],
      ['afoo', true],
      ['afoob', false],
      ['monkey\nfoo', true],
      ['mon\nkeyfoo', true],
    ],
  },
  {
    pattern: '%foo%',
    flags: '',
    inputs: [
      ['foo', true],
      ['foobar', true],
      ['bar', false],
      ['Foo', false],
      ['FOO', false],
      ['fo', false],
      ['fooa', true],
      ['afoo', true],
      ['afoob', true],
      ['mon\nfoo\nkey', true],
      ['m\nonfooke\ny', true],
    ],
  },
  {
    pattern: '%foo\nbar%',
    flags: '',
    inputs: [
      ['foo\nbar', true],
      ['foo\nbar\n', true],
      ['foo\nbar\nbaz', true],
      ['monkey\nfoo\nbar', true],
    ],
  },
];
