FROM Dockerfile.base
EXPOSE 4849
ENTRYPOINT ["/bin/sh", "-c"]
ENV LITESTREAM=1
ENV NUM_SYNC_WORKERS=0
CMD ["(./restore-litestream-db.sh || true) && npx tsx ../../apps/zbugs/zero.config.ts && litestream replicate -config /opt/app/prod/sandbox/replication-manager.yml"]
