/**
 * Generated by tsnapi — public API snapshot of `@rocicorp/zero/server/adapters/postgresjs`
 */
// #region Re-exports
export * from '../../../zero-server/src/adapters/postgresjs.ts';
// #endregion
