name = "zero-service-runner"
main = "../../packages/zero-cache/src/services/index.ts"
compatibility_date = "2024-04-03"
node_compat = true
logpush = true
durable_objects.bindings = [
  { name = "runnerDO", class_name = "RunnerDO" },
]

[vars]
LOG_LEVEL = "debug"
UPSTREAM_URI = "postgresql://user:password@add.your.host.ip:6432/postgres"
SYNC_REPLICA_URI = "postgres://user:password@add.your.host.ip:6433/postgres"


[[migrations]]
tag = "v1"
new_classes = ["RunnerDO"]

[build]
# don't watch all resources because we want to run without --persist when
# possible, so restarts delete data.
watch_dir = "../../packages/zero-cache/src/services"

#[triggers]
#crons = [ "*/5 * * * *" ] # ever 5 mins for AuthDO connection revalidation
