name: Bencher

on:
  push:
    branches: main
  workflow_dispatch:
    inputs:
      reset_baseline:
        description: 'Pass --start-point-reset for a one-off baseline update'
        type: boolean
        default: false

jobs:
  file_sizes:
    name: File Sizes
    permissions:
      checks: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
      - uses: bencherdev/bencher@main

      - run: npm ci
      - run: npm run build

      - name: Build npm zero package
        working-directory: packages/zero
        run: |
          npm pack --pack-destination ./out
          mv ./out/*.tgz ./out/zero-package.tgz

      - name: Build zero client single file package
        working-directory: packages/zero
        run: npx tsx tool/build.ts --bundle-sizes --minify

      - name: Compress
        working-directory: packages/zero
        run: brotli out/zero.js

      - name: Upload benchmarks results to bencher.dev
        working-directory: packages/zero
        run: |
          FLAGS=( --start-point main )
          if [[ "${{ inputs.reset_baseline }}" == "true" ]]; then
            FLAGS+=( --start-point-reset --start-point-clone-thresholds )
          fi

          bencher run \
          --project zero \
          --token '${{ secrets.BENCHER_API_TOKEN }}' \
          --adapter json \
          --github-actions '${{ secrets.GITHUB_TOKEN }}' \
          "${FLAGS[@]}" \
          --threshold-measure file-size \
          --threshold-test percentage \
          --threshold-upper-boundary 0.02 \
          --threshold-max-sample-size 2 \
          --err \
          --file-size out/zero-package.tgz \
          --file-size out/zero.js.br \
          --file-size out/zero.js

  perf:
    name: Perf
    permissions:
      checks: write
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
      - uses: bencherdev/bencher@main

      - run: npm ci

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run benchmarks
        working-directory: packages/zero-client
        run: npm run bench -- --browser.name=chromium --outputJson output.json

      - name: Upload benchmarks results to bencher.dev
        working-directory: packages/zero-client
        run: |
          FLAGS=( --start-point main )
          if [[ "${{ inputs.reset_baseline }}" == "true" ]]; then
            FLAGS+=( --start-point-reset --start-point-clone-thresholds )
          fi

          cat output.json |\
          npx tsx ../shared/src/tool/vitest-perf-json-to-bmf.ts |\
          bencher run \
          --project zero \
          --token '${{ secrets.BENCHER_API_TOKEN }}' \
          --adapter json \
          --github-actions '${{ secrets.GITHUB_TOKEN }}' \
          "${FLAGS[@]}" \
          --threshold-measure throughput \
          --threshold-test t_test \
          --threshold-lower-boundary 0.90 \
          --err
