name: Bencher

on:
  push:
    branches: main

jobs:
  playwright-install:
    name: Install Playwright
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24.x
          cache: 'npm'
      - run: npm ci
      - uses: ./.github/actions/playwright-install

  perf:
    name: Perf
    needs: playwright-install
    uses: ./.github/workflows/reusable-benchmark.yml
    strategy:
      matrix:
        package:
          - name: 'shared'
            directory: 'packages/shared'
          - name: 'zero-client'
            directory: 'packages/zero-client'
          - name: 'zero-cache'
            directory: 'packages/zero-cache'
          - name: 'zql-benchmarks'
            directory: 'packages/zql-benchmarks'
    with:
      package_name: ${{ matrix.package.name }}
      working_directory: ${{ matrix.package.directory }}
    secrets:
      BENCHER_API_TOKEN: ${{ secrets.BENCHER_API_TOKEN }}
