name: Bencher File Sizes

on:
  push:
    branches: [main]

permissions: {}

jobs:
  file_sizes:
    name: File Sizes
    permissions:
      contents: read
      checks: write # Required by Bencher to publish check runs.
      pull-requests: write # Required by Bencher to publish PR results.
    uses: ./.github/workflows/reusable-file-sizes.yml
