name: Bencher File Sizes

on:
  push:
    branches: main

jobs:
  file_sizes:
    name: File Sizes
    uses: ./.github/workflows/reusable-file-sizes.yml
    secrets:
      BENCHER_API_TOKEN: ${{ secrets.BENCHER_API_TOKEN }}
