name: Bencher PR

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  playwright-install:
    name: Install Playwright
    if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository
    permissions:
      contents: read
    runs-on: [self-hosted, benchmark]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
      - uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # v6
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6

        with:
          node-version: 24.x
      - run: pnpm install --frozen-lockfile
      - uses: ./.github/actions/playwright-install

  perf:
    name: Perf PR
    # DO NOT REMOVE: For handling Fork PRs see Pull Requests from Forks
    if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository
    needs: playwright-install
    permissions:
      contents: read
      checks: write
      pull-requests: write
    uses: ./.github/workflows/reusable-benchmark.yml
    strategy:
      fail-fast: false
      matrix:
        package:
          - name: 'shared'
            directory: 'packages/shared'
            ci_id: 'shared-perf'
          - name: 'zero-client'
            directory: 'packages/zero-client'
            ci_id: 'perf'
          - name: 'zero-cache'
            directory: 'packages/zero-cache'
            ci_id: 'zero-cache-perf'
          - name: 'zql-benchmarks'
            directory: 'packages/zql-benchmarks'
            ci_id: 'zql'
    with:
      package_name: ${{ matrix.package.name }}
      working_directory: ${{ matrix.package.directory }}
      ci_id: ${{ matrix.package.ci_id }}
      is_pr: true
      base_ref: ${{ github.event.pull_request.base.ref }}
      head_ref: ${{ github.event.pull_request.head.ref }}
      base_sha: ${{ github.event.pull_request.base.sha }}
    secrets:
      BENCHER_API_TOKEN: ${{ secrets.BENCHER_API_TOKEN }}
