name: Bencher Perf

on:
  push:
    branches: main

jobs:
  throughput:
    name: Bencher Throughput
    permissions:
      checks: write
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
      - uses: bencherdev/bencher@main

      - run: npm ci

      - name: Install Playwright Deps
        run: npx playwright install --with-deps

      - name: Run benchmarks
        working-directory: packages/zero-client
        run: npm run bench -- --outputJson output.json

      - name: Track benchmarks with Bencher
        working-directory: packages/zero-client
        run: |
          cat output.json |\
          npx tsx ../shared/src/tool/vitest-perf-json-to-bmf.ts |\
          bencher run \
          --project zero-perf \
          --token '${{ secrets.BENCHER_API_TOKEN }}' \
          --adapter json \
          --github-actions '${{ secrets.GITHUB_TOKEN }}' \
          --branch "$GITHUB_HEAD_REF" \
          --start-point main \
          --threshold-measure throughput \
          --threshold-test percentage \
          --threshold-lower-boundary 0.05 \
          --threshold-max-sample-size 2 \
          --err
