name: Bencher PR

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  playwright-install:
    name: Install Playwright
    if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24.x
          cache: 'npm'
      - run: npm ci
      - uses: ./.github/actions/playwright-install

  perf:
    name: Perf PR
    # DO NOT REMOVE: For handling Fork PRs see Pull Requests from Forks
    if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository
    needs: playwright-install
    uses: ./.github/workflows/reusable-benchmark.yml
    strategy:
      matrix:
        package:
          - name: 'shared'
            directory: 'packages/shared'
            ci_id: 'shared-perf'
          - name: 'zero-client'
            directory: 'packages/zero-client'
            ci_id: 'perf'
          - name: 'zero-cache'
            directory: 'packages/zero-cache'
            ci_id: 'zero-cache-perf'
          - name: 'zql-benchmarks'
            directory: 'packages/zql-benchmarks'
            ci_id: 'zql'
    with:
      package_name: ${{ matrix.package.name }}
      working_directory: ${{ matrix.package.directory }}
      ci_id: ${{ matrix.package.ci_id }}
      is_pr: true
      base_ref: ${{ github.event.pull_request.base.ref }}
      head_ref: ${{ github.event.pull_request.head.ref }}
      base_sha: ${{ github.event.pull_request.base.sha }}
    secrets:
      BENCHER_API_TOKEN: ${{ secrets.BENCHER_API_TOKEN }}
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
