name: Bencher

on:
  push:
    branches: main

jobs:
  perf:
    name: Perf
    uses: ./.github/workflows/reusable-benchmark.yml
    strategy:
      matrix:
        package:
          - name: 'shared'
            directory: 'packages/shared'
          - name: 'zero-client'
            directory: 'packages/zero-client'
          - name: 'zero-cache'
            directory: 'packages/zero-cache'
          - name: 'zql-benchmarks'
            directory: 'packages/zql-benchmarks'
    with:
      package_name: ${{ matrix.package.name }}
      working_directory: ${{ matrix.package.directory }}
    secrets:
      BENCHER_API_TOKEN: ${{ secrets.BENCHER_API_TOKEN }}
