name: Replicache Bundle Size

on:
  push:
    branches: [main]
    paths:
      - 'packages/replicache/**'

jobs:
  bundle-size:
    name: Bundle Sizes Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # v6
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6

        with:
          node-version: 24.x
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm --filter replicache run build-bundle-sizes
      - run: brotli packages/replicache/out/*

      # Builds bundles then measures bundles sizes and stores them to a file
      - name: Measure bundles
        run: npx tsx tool/bundle-sizes.ts --bundles replicache.mjs replicache.mjs.br replicache.min.mjs replicache.min.mjs.br | tee bundle-sizes.json
        working-directory: packages/replicache

      # Run `github-action-benchmark` action
      - name: Store bundle size
        uses: rhysd/github-action-benchmark@52576c92bccf6ac60c8223ec7eb2565637cae9ba # v1
        with:
          name: 'Bundle Sizes'
          tool: 'customSmallerIsBetter'
          output-file-path: packages/replicache/bundle-sizes.json
          fail-on-alert: true
          github-token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          benchmark-data-dir-path: bundle-sizes
          auto-push: true
          alert-threshold: '105%'
          comment-on-alert: true
