name: Perf Tests Smoke

on:
  pull_request:
    branches: [main]
  merge_group:
    branches: [main]

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  benchmark-smoke:
    name: Performance runner smoke test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'npm'

      - name: configure npm auth token
        run: npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}

      - run: npm ci

      - name: Install Playwright Deps
        run: npx playwright install --with-deps

      - run: npm run build-perf
        working-directory: packages/replicache

      - name: Run benchmark
        run: |
          node packages/replicache/perf/runner.js --format=json --run='populate 1024x1000 \(clean, indexes: 0\)'
        shell: bash
