name: Perf Tests Smoke

on:
  pull_request:
    branches: [main]

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  benchmark-smoke:
    name: Performance runner smoke test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Cache node_modules
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            node_modules/.vite-temp
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-
      - run: npm ci
      - name: Cache Playwright
        id: cache-playwright
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            playwright-${{ runner.os }}-
      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run benchmark
        shell: bash
        working-directory: packages/replicache-perf
        run: |
          npm run build
          npx tsx src/runner.ts --format=json --run='populate 1024x1000 \(clean, indexes: 0\)'
