name: Verify Package Dependencies

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  verify-deps:
    name: Verify Package Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 23.x
      - run: npm install --prefix tools/verify-package-deps
      - run: npm run verify-deps
